jsonCallback ([
	{"quote":"Life isn’t about getting and having, it’s about giving and being.","author":"Kevin Kruse"},
	{"quote":"Whatever the mind of man can conceive and believe, it can achieve.","author":"Napoleon Hill"},
	{"quote":"Strive not to be a success, but rather to be of value.","author":"Albert Einstein"},
	{"quote":"Remember no one can make you feel inferior without your consent.","author":"Eleanor Roosevelt"},
	{"quote":"I attribute my success to this: I never gave or took any excuse.","author":"Florence Nightingale"},
	{"quote":"You miss 100% of the shots you don’t take.","author":"Wayne Gretzky"},
	{"quote":"You may be disappointed if you fail, but you are doomed if you don’t try.","author":"Beverly Sills"},
	{"quote":"The most difficult thing is the decision to act, the rest is merely tenacity.","author":"Amelia Earhart"},
	{"quote":"Every strike brings me closer to the next home run.","author":"Babe Ruth"},
	{"quote":"Definiteness of purpose is the starting point of all achievement.","author":"W. Clement Stone"},
	{"quote":"Definiteness of purpose is the starting point of all achievement.","author":"W. Clement Stone"},
	{"quote":"We must balance conspicuous consumption with conscious capitalism.","author":"Kevin Kruse"},
	{"quote":"Life is what happens to you while you’re busy making other plans.","author":"John Lennon"},
	{"quote":"We become what we think about.","author":"Earl Nightingale"},
	{"quote":"Life is what we make it, always has been, always will be.","author":"Grandma Moses"},
	{"quote":"Life is 10% what happens to me and 90% of how I react to it.","author":"Charles Swindoll"},
	{"quote":"The most common way people give up their power is by thinking they don’t have any.","author":"Alice Walker"},
	{"quote":"The mind is everything. What you think you become.","author":"Buddha"},
	{"quote":"The best time to plant a tree was 20 years ago. The second best time is now.","author":"Chinese Proverb"},
	{"quote":"An unexamined life is not worth living.","author":"Socrates"},
	{"quote":"Eighty percent of success is showing up.","author":"Woody Allen"},
	{"quote":"Your time is limited, so don’t waste it living someone else’s life.","author":"Steve Jobs"},
	{"quote":"Winning isn’t everything, but wanting to win is.","author":"Vince Lombardi"},
	{"quote":"I am not a product of my circumstances. I am a product of my decisions.","author":"Stephen Covey"},
	{"quote":"Every child is an artist.  The problem is how to remain an artist once he grows up.","author":"Pablo Picasso"},
	{"quote":"You can never cross the ocean until you have the courage to lose sight of the shore.","author":"Christopher Columbus"},
	{"quote":"Either you run the day, or the day runs you.","author":"Jim Rohn"},
	{"quote":"Whether you think you can or you think you can’t, you’re right.","author":"Henry Ford"},
	{"quote":"The two most important days in your life are the day you are born and the day you find out why.","author":"Mark Twain"},
	{"quote":"The question isn’t who is going to let me; it’s who is going to stop me.","author":"Ayn Rand"},
	{"quote":"The best revenge is massive success.","author":"Frank Sinatra"},
	{"quote":"It’s not the years in your life that count. It’s the life in your years.","author":"Abraham Lincoln"},
	{"quote":"Life shrinks or expands in proportion to one’s courage.","author":"Anais Nin"},
	{"quote":"There is only one way to avoid criticism: do nothing, say nothing, and be nothing.","author":"Aristotle"},
	{"quote":"Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.","author":"Jesus"},
	{"quote":"The only person you are destined to become is the person you decide to be.","author":"Ralph Waldo Emerson"},
	{"quote":"Go confidently in the direction of your dreams.  Live the life you have imagined.","author":"Henry David Thoreau"},
	{"quote":"Certain things catch your eye, but pursue only those that capture the heart.","author":" Ancient Indian Proverb"},
	{"quote":"Believe you can and you’re halfway there.","author":"Theodore Roosevelt"},
	{"quote":"Everything you’ve ever wanted is on the other side of fear.","author":"George Addair"},
	{"quote":"Teach thy tongue to say, “I do not know,” and thous shalt progress.","author":"Maimonides"},
	{"quote":"Start where you are. Use what you have.  Do what you can.","author":"Arthur Ashe"},
	{"quote":"Fall seven times and stand up eight.","author":"Japanese Proverb"},
	{"quote":"Change your thoughts and you change your world.","author":"Norman Vincent Peale"},
	{"quote":"Either write something worth reading or do something worth writing.","author":"Benjamin Franklin"},
	{"quote":"Nothing is impossible, the word itself says, “I’m possible!”","author":"Audrey Hepburn"},
	{"quote":"The only way to do great work is to love what you do.","author":"Steve Jobs"},
	{"quote":"If you can dream it, you can achieve it.","author":"Zig Ziglar"},
	{"quote":"There are no traffic jams along the extra mile.","author":"Roger Staubach"},
	{"quote":"It is never too late to be what you might have been.","author":"George Eliot"}
]);